OUTPUT_DIRS:
  NPM_DIRECTORY: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/test_npm'
  EPI_BASIC_DIR: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/test_epi_basic'
  EPI_REGION_DIR: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/test_epi_region'
  EVAL_BASIC_DIR: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/test_results_basic'
  EVAL_REGION_DIR: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/test_results_region'

LOG_DIR: 'log'

METH_FILE: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/epiclomal_input/input_Epiclomal_test_pye_1.tsv.gz'
REGION_FILE: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/epiclomal_input/regionIDs_input_Epiclomal_test_pye_1.tsv.gz'
TRUE_FILE: '/shahlab/mandronescu/EPI-70_Smallwood2014/data_process_Smallwood2014/true_clone_membership.txt.gz'
TRUE_PREVALENCES: 'None'

NUM_EPI_ITERS: 1000

PARAMS:
  NPM:
    index: 'ch'
    max_k: 10
    impute: 0
    use_cache: 1
  EPICLOMAL:
    K: 10
    slsbulk_iterations: 10
    mu_has_k: True
    convergence_tolerange: 1e-4
    max_num_iters: 1000
    Bishop_model_selection: False
    check_uncertainty: True
    config_file: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/inputs/config1.yaml'

SOFTWARE:
  hclust_software: '/shahlab/pye/projects/epiclomal/Epiclomal/scripts/hclust.R'
  eval_software: '/shahlab/pye/projects/epiclomal/Epiclomal/scripts/eval_epiclomal.R'
