PROCESS_REAL_DATA_DIR: '../../../process_real_data'

DATA_ID: 'process_Smallwood2014'
OUTDIR: 'process_Smallwood2014'

COV_DIR: 'data_Smallwood2014/cov'
CELL_PATTERN: ".cov.txt"
# All the cell names with the pattern will be extracted from COV_DIR

REGION_FILE: 'data_Smallwood2014/CGI_mm10_regions.txt'
TRUE_FILE: 'data_Smallwood2014/true_clone_membership.txt.gz'

CPG_COORDS:
  NAME_REGIONS: 'process_Smallwood2014'
  GENOME_LIBRARY: 'BSgenome.Mmusculus.UCSC.mm10'
  TYPE_OF_C: 'CpG'

CELL_BASED_METH:
  INCLUDE_CHRY: 1
  DATA_TYPE: 'bismark'
  GENOME: 'mouse'

STATS_METHYLATION:
  #NUM_CELLS_CUTOFF: 5
  #MISS_PROP_CUTOFF: 0.95
  #NLOCI_CUTOFF: 0.0
  ALL_CUTOFFS: 
    - "0_0.95_10000"
    - "0_0.95_15000"
    - "0_0.95_20000"
    - "0_0.95_50000"
    - "0_1_0.01"
    - "0_1_0.05"    
    - "0_1_0.1"
    - "0_0.95_0.01"
    - "0_0.95_0.05"    
    - "0_0.95_0.1"       
  FILTER_REGIONS_SAME_METH: 1
  #FILTER_REGIONS_SAME_METH: Null
  PLOT_HEATMAP_FILTERED: 1
  PLOT_HEATMAP_UNFILTERED: 0

FILTER_REGIONS:
  FILTER: False
  COEF_THRESHOLD: 0.95
  MEAN_DIFF_THRESHOLD: 0.05
  N_TO_KEEP: 1000

READY_EPICLOMAL:
  FILTER_CPG_NO_DATA: 0
  LUODIAMOND: 0

