OUTPUT_DIRS:
  DATA_DIRECTORY: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/synthetic'
  NPM_DIRECTORY: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/simple_hclust'
  EPI_BASIC_DIR: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/epiclomal_basic'
  EPI_REGION_DIR: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/epiclomal_region'
  EVAL_BASIC_DIR: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/results_basic'
  EVAL_REGION_DIR: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/results_region'

LOG_DIR: 'log'

PARAMS:
  ALL:
    prevalences: '0.20_0.20_0.15_0.15_0.10'
  GENERATE_SYNTHETIC:
    saveall: 0
    verbose: 0
    read_size: '10_2'
    region_size_type: 'multinomial_equal'
    genotype_prob: 'dirichlet'
    num_regions: 25
    num_clones: 5
    num_cells: 500
    plot_data: 1
    seed: 31
    prop_add_var: '0_0.5'
    prop_cpd_flip: 1
    num_samples: 1
    missing_probability: 0.6
    error_probability: '0.001_0.001'
    num_loci: 5000
    given_dir_complete: 1
    phylogenetic_generation: 1
    percent_regions_dirichlet_param: 0.85
    dirichlet_param_genotype_prob: '90_10'
  NPM:
    index: 'ch'
    max_k: 10
    impute: 0
    use_cache: 0
  EPICLOMAL:
    K: 10
    slsbulk_iterations: 10
    mu_has_k: True
    convergence_tolerange: 1e-4
    max_num_iters: 1000
    Bishop_model_selection: False
    check_uncertainty: True
    config_file: '/shahlab/pye/projects/epiclomal/Epiclomal/examples/inputs/config1.yaml'

SOFTWARE:
  generate_synthetic_software: '/shahlab/pye/projects/epiclomal/Epiclomal/scripts/generate_synthetic.R'
  euclidean_clust_software: '/shahlab/pye/projects/epiclomal/Epiclomal/scripts/non_probabilistic_methods/euclideanclust.R'
  hamming_clust_software: '/shahlab/pye/projects/epiclomal/Epiclomal/scripts/non_probabilistic_methods/hammingclust.R'
  pearson_clust_software: '/shahlab/pye/projects/epiclomal/Epiclomal/scripts/non_probabilistic_methods/pearsonclust.R'
  density_cut_software: '/shahlab/pye/projects/epiclomal/Epiclomal/scripts/non_probabilistic_methods/densitycut.R'
  epiclomal_software: '/shahlab/pye/projects/epiclomal/Epiclomal/epiclomal/epiclomal.py'
  cluster_eval_software: '/shahlab/pye/projects/epiclomal/Epiclomal/epiclomal/evalutate_clustering.py'
  eval_software: '/shahlab/pye/projects/epiclomal/Epiclomal/scripts/eval_epiclomal.R'
