PROCESS_REAL_DATA_DIR: '/shahlab/pye/projects/epiclomal/Epiclomal/process_real_data'

DATA_ID: 'test_pye_1'
OUTDIR: '/shahlab/pye/projects/epiclomal/examples/test_process_real_data'

DATA_DIR: '/shahlab/mandronescu/EPI-70_Smallwood2014/data_process_Smallwood2014/cov'

cells:
  [GSM1370535_2i_1,
  GSM1370536_2i_2,
  GSM1370537_2i_3,
  GSM1370538_2i_4,
  GSM1370539_2i_5,
  GSM1370540_2i_6,
  GSM1370541_2i_7,
  GSM1370542_2i_8,
  GSM1370543_2i_9,
  GSM1370544_2i_10,
  GSM1370545_2i_11,
  GSM1370546_2i_12,
  GSM1370555_Ser1,
  GSM1370556_Ser2,
  GSM1370557_Ser3,
  GSM1370558_Ser4,
  GSM1370559_Ser5,
  GSM1370560_Ser6,
  GSM1370561_Ser7,
  GSM1370562_Ser8,
  GSM1370563_Ser9,
  GSM1370564_Ser10,
  GSM1370565_Ser11,
  GSM1370566_Ser12,
  GSM1370567_Ser13,
  GSM1370568_Ser14,
  GSM1370569_Ser15,
  GSM1370570_Ser16,
  GSM1370571_Ser17,
  GSM1370572_Ser18,
  GSM1370573_Ser19,
  GSM1370574_Ser20]

REGION_FILE: '/shahlab/mandronescu/EPI-70_Smallwood2014/data_process_Smallwood2014/CGI_mm10_regions.txt'
TRUE_FILE: '/shahlab/mandronescu/EPI-70_Smallwood2014/data_process_Smallwood2014/true_clone_membership.txt.gz'

CPG_COORDS:
  NAME_REGIONS: 'regions'
  GENOME_LIBRARY: 'BSgenome.Mmusculus.UCSC.mm10'
  TYPE_OF_C: 'CpG'

CELL_BASED_METH:
  INCLUDE_CHRY: 1
  DATA_TYPE: 'bismark'
  GENOME: 'mouse'

STATS_METHYLATION:
  NUM_CELLS_CUTOFF: 5
  MISS_PROP_CUTOFF: 0.95
  NLOCI_CUTOFF: 0.0
  ALL_CUTOFFS: "0_0.95_10000"
  FILTER_REGIONS_SAME_METH: Null
  PLOT_HEATMAP_UNFILTERED: 1
  PLOT_HEATMAP_UNFILTERED: 1

FILTER_REGIONS:
  FILTER: True
  COEF_THRESHOLD: 0.95
  MEAN_DIFF_THRESHOLD: 0.05

READY_EPICLOMAL:
  FILTER_CPG_NO_DATA: 0
  LUODIAMOND: 0
